set max_error_count=300;
LOAD DATA INFILE 'WWWfolder_temporario/cand_WWWano.txt' INTO TABLE cand_WWWano
FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n'
(@DATA_GERACAO, @HORA_GERACAO, ANO_ELEICAO, NUM_TURNO, DESCRICAO_ELEICAO, SIGLA_UF, SIGLA_UE, DESCRICAO_UE, CODIGO_CARGO, DESCRICAO_CARGO, NOME_CANDIDATO, SEQUENCIAL_CANDIDATO, NUMERO_CANDIDATO, NOME_URNA_CANDIDATO, COD_SITUACAO_CANDIDATURA, DES_SITUACAO_CANDIDATURA, NUMERO_PARTIDO, SIGLA_PARTIDO, NOME_PARTIDO, CODIGO_LEGENDA, SIGLA_LEGENDA, COMPOSICAO_LEGENDA, NOME_LEGENDA, CODIGO_OCUPACAO, DESCRICAO_OCUPACAO, @DATA_NASC_AUX, NUM_TITULO_ELEITORAL_CANDIDATO, IDADE_DATA_ELEICAO, CODIGO_SEXO, DESCRICAO_SEXO, COD_GRAU_INSTRUCAO, DESCRICAO_GRAU_INSTRUCAO, CODIGO_ESTADO_CIVIL, DESCRICAO_ESTADO_CIVIL, CODIGO_NACIONALIDADE, DESCRICAO_NACIONALIDADE, SIGLA_UF_NASCIMENTO, CODIGO_MUNICIPIO_NASCIMENTO, NOME_MUNICIPIO_NASCIMENTO, DESPESA_MAX_CAMPANHA, COD_SIT_TOT_TURNO, DESC_SIT_TOT_TURNO)
set DATA_HORA_GERACAO = str_to_date(CONCAT_WS(' ', @DATA_GERACAO, @HORA_GERACAO), '%d/%m/%Y %H:%i:%s'), DATA_NASCIMENTO = str_to_date(corrige_data(@DATA_NASC_AUX), '%Y%m%d');
show warnings;
